// shows.ts
export interface Show {
  id: string
  date: string
  day: string
  year: string
  venue: string
  city: string
  withBands: string[]
  posterUrl?: string
}

export const showsByYear: Record<string, Show[]> = {
  '2025': [
    {
      id: '1',
      date: '2025-10-22',
      day: 'October 22nd',
      year: '2025',
      venue: 'Secret Place',
      city: 'Montpellier (FR)',
      withBands: ['The Great Old Ones', 'Eternal Hunt'],
      posterUrl: 'show_posters/2025-10-22.jpg',
    },
    {
      id: '2',
      date: '2025-05-23',
      day: 'May 23rd',
      year: '2025',
      venue: 'Mojo',
      city: 'St Sulpice (FR)',
      withBands: ['Defekt', 'Lava Veins'],
      posterUrl: 'show_posters/2025-05-23.jpg',
    },
    {
      id: '3',
      date: '2025-05-22',
      day: 'May 22nd',
      year: '2025',
      venue: 'Secret Place',
      city: 'Montpellier (FR)',
      withBands: ['Ondfødt'],
      posterUrl: 'show_posters/2025-05-22.jpg',
    },
    {
      id: '4',
      date: '2025-04-26',
      day: 'April 26th',
      year: '2025',
      venue: 'Les 3 Fontaines',
      city: 'Les Martys (FR)',
      withBands: ['Out of Mana', 'Cynocephal', 'Vayron'],
      posterUrl: 'show_posters/2025-04-26.jpg',
    },
    {
      id: '5',
      date: '2025-04-18',
      day: 'April 18th',
      year: '2025',
      venue: 'Axis Musique',
      city: 'Toulouse (FR)',
      withBands: ['Ashen Heart', 'EverRise'],
      posterUrl: 'show_posters/2025-04-18.jpg',
    },
    {
      id: '6',
      date: '2025-02-01',
      day: 'February 1st',
      year: '2025',
      venue: 'Cluricaume Café',
      city: 'Poitiers (FR)',
      withBands: ['Ataraxy'],
      posterUrl: 'show_posters/2025-02-01.jpg',
    },
  ],
  '2024': [
    {
      id: '7',
      date: '2024-10-03',
      day: 'October 3rd',
      year: '2024',
      venue: "Fotomat'",
      city: 'Clermont-Ferrand (FR)',
      withBands: ['Mind Repress'],
      posterUrl: 'show_posters/2024-10-03.jpg',
    },
    {
      id: '8',
      date: '2024-04-14',
      day: 'April 14th',
      year: '2024',
      venue: 'Chorus',
      city: 'Toulouse (FR)',
      withBands: ['Crazy Hammer', 'Dead Tree Seeds', 'Minds'],
      posterUrl: 'show_posters/2024-04-14.jpg',
    },
    {
      id: '9',
      date: '2024-03-16',
      day: 'March 16th',
      year: '2024',
      venue: "Les Barthes – Moun's",
      city: 'Les Barthes (FR)',
      withBands: ['EverRise', 'Corporal Punishment'],
      posterUrl: 'show_posters/2024-03-16.jpg',
    },
  ],
  '2023': [
    {
      id: '10',
      date: '2023-12-01',
      day: 'December 1st',
      year: '2023',
      venue: 'Salem',
      city: 'Bordeaux (FR)',
      withBands: ['Ad Patres', 'Trepanator'],
      posterUrl: 'show_posters/2023-12-01.jpg',
    },
    {
      id: '11',
      date: '2023-05-26',
      day: 'May 26th',
      year: '2023',
      venue: 'Axis Musique',
      city: 'Toulouse (FR)',
      withBands: ['ANZV', 'Fall of Seraphs'],
      posterUrl: 'show_posters/2023-05-26.jpg',
    },
    {
      id: '12',
      date: '2023-04-01',
      day: 'April 1st',
      year: '2023',
      venue: 'Le Jean Jaurès',
      city: 'Castres (FR)',
      withBands: ['Spit the Curse'],
      posterUrl: 'show_posters/2023-04-01.jpg',
    },
    {
      id: '13',
      date: '2023-03-31',
      day: 'March 31st',
      year: '2023',
      venue: 'Secret Place',
      city: 'Montpellier (FR)',
      withBands: ['Noctem'],
      posterUrl: 'show_posters/2023-03-31.jpg',
    },
    {
      id: '14',
      date: '2023-03-04',
      day: 'March 4th',
      year: '2023',
      venue: 'Salle des fêtes',
      city: 'Escondeaux (FR)',
      withBands: ['Tempest Fate', 'Earthquake'],
      posterUrl: 'show_posters/2023-03-04.jpg',
    },
    {
      id: '15',
      date: '2023-01-27',
      day: 'January 27th',
      year: '2023',
      venue: "L'Engrenage",
      city: 'Toulouse (FR)',
      withBands: ['Skaphos', 'Silhouette'],
      posterUrl: 'show_posters/2023-01-27.jpg',
    },
    {
      id: '16',
      date: '2023-01-26',
      day: 'January 26th',
      year: '2023',
      venue: "L'Antidote",
      city: 'Bordeaux (FR)',
      withBands: ['Skaphos', 'Fièvres'],
      posterUrl: 'show_posters/2023-01-26.jpg',
    },
  ],
  '2022': [
    {
      id: '17',
      date: '2022-06-25',
      day: 'June 25th',
      year: '2022',
      venue: 'Celtic Pub',
      city: 'Tarbes (FR)',
      withBands: ['EverRise'],
      posterUrl: 'show_posters/2022-06-25.jpg',
    },
    {
      id: '18',
      date: '2022-06-10',
      day: 'June 10th',
      year: '2022',
      venue: 'Cave à Rock',
      city: 'Toulouse (FR)',
      withBands: ['Beneath On Obscure Sky', 'From Dusk to Dawn'],
      posterUrl: 'show_posters/2022-06-10.jpg',
    },
  ],
}
